[project]
name = "csv-profiler"
version = "0.1.0"
description = "Simple CSV profiling tool"
requires-python = ">=3.12"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
